### ISSUE TITLE
ESM Bunder component registration not functioning

### ISSUE THREAD

**Issue by carolinecblaker** [johndatserakis/vue-mailchimp-email-signup-form#3]
In your registration instructions, you specify:

`import { VueMailchimpEmailSignupForm } from "vue-mailchimp-email-signup-form";
Vue.component("vue-mailchimp-email-signup-form", VueMailchimpEmailSignupForm);`

After I get past:
`import { VueMailchimpEmailSignupForm } from "vue-mailchimp-email-signup-form";`

I registered thusly:

`components: {
		draggable: VueDraggableNext,
		vue-mailchimp-email-signup-form: VueMailchimpEmailSignupForm,
                // ...etc..
	  },`

And then I added the component:

`<vuemailchimpemailsignupform
								:element-id="'first-email-signup-form'"
								:url="'https://xxx.us14.list-manage.com/subscribe/post?u=xx&amp;id=xx&amp;f_id=xx'"
								:title="'Get in on the xx Beta'"
								:subtitle="'We take privacy seriously and we will never spam, distribute, or sell your information.'"
								/>`

The following error occurred:

`[Vue warn]: Property "$createElement" was accessed during render but is not defined on instance. 
  at <VueMailchimpEmailSignupForm element-id="first-email-signup-form" url="https://ssa123.us14.list-manage.com/subscribe/post?u=784f087b407c7a870d05e44db&id=1a7954972a&f_id=003e8ce0f0" title="Get in on the ssa123 Beta"  ... > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="fade" > 
  at <App>
warn @ runtime-core.esm-bundler.js:198
get @ runtime-core.esm-bundler.js:3317
__vue_render__ @ react-mailchimp-email-signup-form.es.js:176
renderComponentRoot @ runtime-core.esm-bundler.js:1047
componentUpdateFn @ runtime-core.esm-bundler.js:5752
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
setupRenderEffect @ runtime-core.esm-bundler.js:5880
mountComponent @ runtime-core.esm-bundler.js:5662
processComponent @ runtime-core.esm-bundler.js:5620
patch @ runtime-core.esm-bundler.js:5222
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
componentUpdateFn @ runtime-core.esm-bundler.js:5832
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
callWithErrorHandling @ runtime-core.esm-bundler.js:315
flushJobs @ runtime-core.esm-bundler.js:545
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:437
queueJob @ runtime-core.esm-bundler.js:431
eval @ runtime-core.esm-bundler.js:5864
triggerEffect @ reactivity.esm-bundler.js:426
triggerEffects @ reactivity.esm-bundler.js:416
trigger @ reactivity.esm-bundler.js:388
set @ reactivity.esm-bundler.js:555
set @ runtime-core.esm-bundler.js:3329
openModal @ index.js:223
firePitch @ index.js:230
callWithErrorHandling @ runtime-core.esm-bundler.js:315
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:324
invoker @ runtime-dom.esm-bundler.js:625
runtime-core.esm-bundler.js:198 [Vue warn]: Property "_self" was accessed during render but is not defined on instance. 
  at <VueMailchimpEmailSignupForm element-id="first-email-signup-form" url="https://ssa123.us14.list-manage.com/subscribe/post?u=784f087b407c7a870d05e44db&id=1a7954972a&f_id=003e8ce0f0" title="Get in on the ssa123 Beta"  ... > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="fade" > 
  at <App>
warn @ runtime-core.esm-bundler.js:198
get @ runtime-core.esm-bundler.js:3317
__vue_render__ @ react-mailchimp-email-signup-form.es.js:177
renderComponentRoot @ runtime-core.esm-bundler.js:1047
componentUpdateFn @ runtime-core.esm-bundler.js:5752
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
setupRenderEffect @ runtime-core.esm-bundler.js:5880
mountComponent @ runtime-core.esm-bundler.js:5662
processComponent @ runtime-core.esm-bundler.js:5620
patch @ runtime-core.esm-bundler.js:5222
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
componentUpdateFn @ runtime-core.esm-bundler.js:5832
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
callWithErrorHandling @ runtime-core.esm-bundler.js:315
flushJobs @ runtime-core.esm-bundler.js:545
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:437
queueJob @ runtime-core.esm-bundler.js:431
eval @ runtime-core.esm-bundler.js:5864
triggerEffect @ reactivity.esm-bundler.js:426
triggerEffects @ reactivity.esm-bundler.js:416
trigger @ reactivity.esm-bundler.js:388
set @ reactivity.esm-bundler.js:555
set @ runtime-core.esm-bundler.js:3329
openModal @ index.js:223
firePitch @ index.js:230
callWithErrorHandling @ runtime-core.esm-bundler.js:315
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:324
invoker @ runtime-dom.esm-bundler.js:625
runtime-core.esm-bundler.js:198 [Vue warn]: Unhandled error during execution of render function 
  at <VueMailchimpEmailSignupForm element-id="first-email-signup-form" url="https://ssa123.us14.list-manage.com/subscribe/post?u=784f087b407c7a870d05e44db&id=1a7954972a&f_id=003e8ce0f0" title="Get in on the ssa123 Beta"  ... > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="fade" > 
  at <App>
warn @ runtime-core.esm-bundler.js:198
logError @ runtime-core.esm-bundler.js:372
handleError @ runtime-core.esm-bundler.js:364
renderComponentRoot @ runtime-core.esm-bundler.js:1076
componentUpdateFn @ runtime-core.esm-bundler.js:5752
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
setupRenderEffect @ runtime-core.esm-bundler.js:5880
mountComponent @ runtime-core.esm-bundler.js:5662
processComponent @ runtime-core.esm-bundler.js:5620
patch @ runtime-core.esm-bundler.js:5222
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
mountChildren @ runtime-core.esm-bundler.js:5406
mountElement @ runtime-core.esm-bundler.js:5316
processElement @ runtime-core.esm-bundler.js:5299
patch @ runtime-core.esm-bundler.js:5219
componentUpdateFn @ runtime-core.esm-bundler.js:5832
run @ reactivity.esm-bundler.js:221
instance.update @ runtime-core.esm-bundler.js:5866
callWithErrorHandling @ runtime-core.esm-bundler.js:315
flushJobs @ runtime-core.esm-bundler.js:545
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:437
queueJob @ runtime-core.esm-bundler.js:431
eval @ runtime-core.esm-bundler.js:5864
triggerEffect @ reactivity.esm-bundler.js:426
triggerEffects @ reactivity.esm-bundler.js:416
trigger @ reactivity.esm-bundler.js:388
set @ reactivity.esm-bundler.js:555
set @ runtime-core.esm-bundler.js:3329
openModal @ index.js:223
firePitch @ index.js:230
callWithErrorHandling @ runtime-core.esm-bundler.js:315
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:324
invoker @ runtime-dom.esm-bundler.js:625
runtime-core.esm-bundler.js:198 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <VueMailchimpEmailSignupForm element-id="first-email-signup-form" url="https://ssa123.us14.list-manage.com/subscribe/post?u=784f087b407c7a870d05e44db&id=1a7954972a&f_id=003e8ce0f0" title="Get in on the ssa123 Beta"  ... > 
  at <BaseTransition appear=false persisted=false mode=undefined  ... > 
  at <Transition name="fade" > 
  at <App>
warn @ runtime-core.esm-bundler.js:198
logError @ runtime-core.esm-bundler.js:372
handleError @ runtime-core.esm-bundler.js:364
callWithErrorHandling @ runtime-core.esm-bundler.js:318
flushJobs @ runtime-core.esm-bundler.js:545
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:437
queueJob @ runtime-core.esm-bundler.js:431
eval @ runtime-core.esm-bundler.js:5864
triggerEffect @ reactivity.esm-bundler.js:426
triggerEffects @ reactivity.esm-bundler.js:416
trigger @ reactivity.esm-bundler.js:388
set @ reactivity.esm-bundler.js:555
set @ runtime-core.esm-bundler.js:3329
openModal @ index.js:223
firePitch @ index.js:230
callWithErrorHandling @ runtime-core.esm-bundler.js:315
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:324
invoker @ runtime-dom.esm-bundler.js:625
react-mailchimp-email-signup-form.es.js:177 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__ (react-mailchimp-email-signup-form.es.js:177:22)
    at renderComponentRoot (runtime-core.esm-bundler.js:1047:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5752:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:221:25)
    at instance.update (runtime-core.esm-bundler.js:5866:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5880:9)
    at mountComponent (runtime-core.esm-bundler.js:5662:9)
    at processComponent (runtime-core.esm-bundler.js:5620:17)
    at patch (runtime-core.esm-bundler.js:5222:21)
    at mountChildren (runtime-core.esm-bundler.js:5406:13)`

LMK if I can be more helpful with this request.

**Comment by johndatserakis** [comment]
Hey there - so it could be a few things:

1. You need dashed in the component name during usage, I think. So use `<vue-mailchimp-email-signup-form ...`.
2. Make sure to register the component specifically like I do in my example:
  ```
  import { VueMailchimpEmailSignupForm } from "vue-mailchimp-email-signup-form";
  Vue.component("vue-mailchimp-email-signup-form", VueMailchimpEmailSignupForm);
  ```
3. What version of Vue are you using? This component is only supported in Vue2, so it won't work in Vue3. Feel free to just take the source code and adjust as needed for Vue3 if that's the case.
